### ISSUE TITLE
Migrate build system to bazel

### ISSUE THREAD

**Issue by miguel250** [senior7515/smf#165]
We will also like to source the third party dependencies source locally.

**Comment by senior7515** [comment]
Great! This is a really good idea. We should port the other build sys too. What do you think ?

**Comment by senior7515** [comment]
For example via the 

'new_http_archive() '

With a repo.BUILD file in 3rdparty/ 

What are you thinking ?

**Comment by noahdesu** [comment]
I've been looking to jump in and test out smf rpc framework. Just looking through some of the issues I ran into this. Is there a plan to move to bazel? Seastar is using Ninja, but there is an open ticket there for migrating to CMake. CMake is so widely deployed that many users would then need to deal with cmake, bazel, and ninja.

**Comment by senior7515** [comment]
hi @noahdesu  !

bazel will be experimental until we feel comfortable w/ it. - don't expect the master branch to have it soon. or to delete cmake. 

I want to build the scala,java code generator as well as py, etc. Managing multiple languages is not very easy w/ anything but buck, pants or bazel or home-grown. 

If it's helpful  - i'm happy to consider keeping cmake for a while if you only plan on using the c++.

The idea is actually to eliminate ninja, cmake, make, etc. 

I have internal repo's of bazel where they act in 2 ways: 

1) You shell out like heron does https://github.com/twitter/heron/blob/master/third_party/yaml-cpp/BUILD#L65-L76

or 

2) you build them manually like gflags: 

https://github.com/gflags/gflags/blob/master/WORKSPACE

**Comment by senior7515** [comment]
also @noahdesu  let me know if u need help testing. 

It works out of the box on fedora 27 - that's what I'm testing on.

**Comment by noahdesu** [comment]
Sounds great, thanks for the explanation.

**Comment by senior7515** [comment]
https://github.com/spotify/bazel-tools

**Comment by senior7515** [comment]
closing this ticket due to inactivity. and #203
