### ISSUE TITLE
smf_gen output option

### ISSUE THREAD

**Issue by noahdesu** [senior7515/smf#175]
future feature request

hacking on cmake build support for smf, i noticed that smf_gen lacks a flexible method for producing output. this is useful for wrangling paths in support of out-of-tree builds.

currently i'm using --print_smf_gen_to_stderr which works alright.

**Comment by senior7515** [comment]
Agreed. Thanks for the report. ! 

Looking forward to an improved build too.

**Comment by senior7515** [comment]
@noahdesu I added support here 

https://github.com/senior7515/smf/pull/176/files


```
➜  smf git:(feature/genpath) ✗ pwd
/home/agallego/workspace/smf
➜  smf git:(feature/genpath) ✗ ./build_debug/src/rpc/smf_gen/smf_gen --filename src/flatbuffers/raft.fbs --output_path=./build_debug --logtostderr
I1208 20:45:40.723206 22621 idl.cc:52] /home/agallego/workspace/smf/build_debug/raft.smf.fb.h
➜  smf git:(feature/genpath) ✗ ls ./build_debug/raft.smf.fb.h 

```

**Comment by senior7515** [comment]
this flag: 

--print_smf_gen_to_stderr

was mostly used for debug as it printed an extra line

I will merge tomorrow if you give it a test and think of other improvements for that

**Comment by noahdesu** [comment]
new invocation looks good. i haven't tried this version, but i did notice another issue with i/o failures. here is smf_gen reporting everything is cool when the fs is read-only:

```
[nwatkins@sapporo asdf]$ chmod a-w .
[nwatkins@sapporo asdf]$ ../src/rpc/smf_gen/smf_gen --filename demo_service.fbs ; echo $?
0
```

**Comment by senior7515** [comment]
Oh ha, it's a bug with the flatbuffers save file. 

Will write our own with proper checks. 

Good testing!!!

**Comment by noahdesu** [comment]
ack. this is working in my tests here

https://github.com/noahdesu/smf/blob/cmake/src/flatbuffers/CMakeLists.txt#L10

**Comment by senior7515** [comment]
Perfect. Will add some unit tests and merge. Traveling tomorrow. So probably on a couple of days when I get home. Thanks for testing

**Comment by senior7515** [comment]
@noahdesu

I fixed the error. Thank you for reporting it! 

```
➜  test git:(feature/genpath) ✗ chmod ugoa-w .                                                                      
➜  test git:(feature/genpath) ✗ ../src/rpc/smf_gen/smf_gen --filename ../../src/flatbuffers/raft.fbs --output_path=.
F1210 05:31:29.413694  7472 main.cc:51] Could not generate file
*** Check failure stack trace: ***
    @     0x7f54d744a138  google::LogMessage::Fail()
    @     0x7f54d744a094  google::LogMessage::SendToLog()
    @     0x7f54d7449a60  google::LogMessage::Flush()
    @     0x7f54d744c914  google::LogMessageFatal::~LogMessageFatal()
    @           0x44c167  main
    @     0x7f54d584103a  __libc_start_main
    @           0x423d4a  _start
[1]    7472 abort (core dumped)  ../src/rpc/smf_gen/smf_gen --filename ../../src/flatbuffers/raft.fbs 
➜  test git:(feature/genpath) ✗ chmod ugoa+w .                                                                      
➜  test git:(feature/genpath) ✗ ../src/rpc/smf_gen/smf_gen --filename ../../src/flatbuffers/raft.fbs --output_path=.
➜  test git:(feature/genpath) ✗ echo $?                      
0

```

**Comment by senior7515** [comment]
in master.
