### ISSUE TITLE
integration tests exit codes

### ISSUE THREAD

**Issue by noahdesu** [senior7515/smf#179]
I'm seeing an issue where the return code for an integration test running under the test_runner.py is not exiting with a non-zero value.

Note below in running the test the `ERROR` lines, followed by printing the exit code of 0. I'm running tests to check that runtime linking paths work alright, but I noticed this as well.

Should this return code be non-zero to avoid missing broken test runs?

```
+ python /smf/ci/..//src/test_runner.py --type integration --binary rpc_recv_timeout_integration_test --directory /smf/ci/..//src/integration_tests/rpc_recv_timeout --git_root /smf/ci/../
TESTRUNNER INFO:2017-12-12 22:16:55,327 test_runner.py:81] 
Test: rpc_recv_timeout_integration_test -c 1
Config: {u'args': [u'-c 1'], 'execution_directory': '/tmp/tmp.Wb4Z03iW3k/3', 'source_directory': '/smf/ci/..//src/integration_tests/rpc_recv_timeout'}
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2017-12-12 22:16:55,562 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2017-12-12 22:16:55,563 [shard 0] smf - rpc_server.cc:64] Starging server:rpc_server{args.ip=, args.flags=1, args.rpc_port=18882, args.http_port=58122, rpc_routes=rpc_handle_router{rpc_service{name=SmfStorage,handles=rpc_service_met
hod_handle{name=Get}}}, limits=rpc_connection_limits{'basic_req_size':256.000 bytes,'bloat_factor': 1.000 bytes,'max_mem':2.000 GB,'res_avail':2.000 GB( 2147483648 )}}
INFO  2017-12-12 22:16:55,563 [shard 0] smf - rpc_server.cc:86] Starting RPC Server...
ERROR 2017-12-12 22:16:55,565 [shard 0] smf - rpc_recv_context.cc:53] Parsing the body of the connnection exceeded max_timeout: 1ms
ERROR 2017-12-12 22:16:55,565 [shard 0] smf - rpc_recv_context.cc:87] Read incorrect number of bytes `0`, expected header: `rpc::header={ compression: none, bitflags: 0, session: 0, size: 300, checksum: 1234234, meta: 0 }`
WARN  2017-12-12 22:16:55,574 [shard 0] smf - rpc_server.cc:114] Stopping rpc server: aborting future accept() calls
WARN  2017-12-12 22:16:55,574 [shard 0] smf - rpc_server.cc:109] Server stopped accepting connections: `std::system_error (error system:103, Software caused connection abort)`
+ echo 'RESULT RETURN CODE 0'
RESULT RETURN CODE 0
```

**Comment by senior7515** [comment]
this test has to ignore error logs tho. 

setting a socket timeout on the server side for reading stale clients is a configurable parameters. 

so the test sets a timeout of 1millisecond. - and waits for 10ms 

so it has to print the error log (which would be an error ? maybe I can set it as a warning on the server side? ) 

and close the socket. 

Thanks for checking. 


```
body_timeout.set_callback(
          [max_timeout = conn->limits->max_body_parsing_duration, conn] {
            LOG_ERROR(
              "Parsing the body of the connnection exceeded max_timeout: {}ms",
              std::chrono::duration_cast<std::chrono::milliseconds>(max_timeout)
                .count());
            conn->set_error("Connection body parsing exceeded timeout");
            conn->socket.shutdown_input();
          });


```

**Comment by senior7515** [comment]
unless i miss something I'll close this ticket. I'll assign to you so you can close it in case I missunderstood. 

thanks again!

**Comment by senior7515** [comment]
is there any other test that has these conditions ?

**Comment by noahdesu** [comment]
maybe my question wasn't really very clear. the cmake add_test feature reports failure for non-zero exit codes. above, the log reports an error, but we get a zero exit code, thus ctest reports success despite the error.

i haven't dug into the exact semantics of this test, so the short version of the question is: is the above error in the log a test failure?

**Comment by senior7515** [comment]
no it is not a failure. the test is correct. cmake is correct to report success.

I didn't communicate it clearly, sorry. 

I was trying to give you background on the reason for the error log. In case of failure we exit (1) on this test. 

the reason you are seeing those error logs is that this is an integration test, so I'm triggering an error manually and I expect it to fail.

**Comment by noahdesu** [comment]
got it! thanks for the clarification it makes sense now.
