### ISSUE TITLE
use cmake ExternalProject_Add

### ISSUE THREAD

**Issue by senior7515** [senior7515/smf#210]
Currently, it is really hard to exclude targets and to set versions, etc on the cmake build

https://cmake.org/cmake/help/v3.0/module/ExternalProject.html

Effectively, it prints a bunch of warnings from different projects, it runs tests and the downside is that only mature projects have guards against them via a simple `-DCMAKE_<PROJ_SPECIFIC_OPT>=OFF`

which means a bunch of custom logic for them. (non pkgfind'd things)

```

Test project /home/agallego/workspace/smf/build_debug
    Start 1: Histogram
1/7 Test #1: Histogram ...............................   Passed    0.05 sec
    Start 2: HistogramLogging
2/7 Test #2: HistogramLogging ........................   Passed    0.03 sec
    Start 3: HistogramAtomic
3/7 Test #3: HistogramAtomic .........................   Passed    0.00 sec
    Start 4: flattests
4/7 Test #4: flattests ...............................   Passed    0.04 sec
    Start 5: smf_histograms_integration_test
5/7 Test #5: smf_histograms_integration_test .........   Passed    0.20 sec
    Start 6: smf_rpc_integration_test
6/7 Test #6: smf_rpc_integration_test ................   Passed    0.25 sec
    Start 7: smf_rpc_recv_timeout_integration_test
7/7 Test #7: smf_rpc_recv_timeout_integration_test ...   Passed    0.20 sec

100% tests passed, 0 tests failed out of 7

```

**Comment by noahdesu** [comment]
I'm a little confused. Do you have some specific examples of things that are wonky/difficult/etc..?

Are you referring to the warning when you run cmake that mention the different policies? I think that's something we can fix pretty easily.

Currently I'm using `smf` as a submodule in a project like this (this includes patches I haven't pushed yet)

```
cmake_minimum_required(VERSION 3.3)
project(verve)

SET(SMF_ENABLE_UNIT_TESTS OFF CACHE BOOL
  "Disable smf unit tests")
SET(SMF_ENABLE_INTEGRATION_TESTS OFF CACHE BOOL
  "Disable build smf integration tests")
SET(SMF_ENABLE_BENCHMARK_TESTS OFF CACHE BOOL
  "Disable build smf benchmarks")
add_subdirectory(smf)

smf_generate_cpp(verve_fbs verve.fbs)

include_directories(
  ${PROJECT_SOURCE_DIR}
  ${PROJECT_BINARY_DIR}
  # include path hacks to be fixed later
  ${PROJECT_SOURCE_DIR}/smf/src
  ${PROJECT_SOURCE_DIR}/smf/src/third_party/flatbuffers/include
  ${PROJECT_BINARY_DIR}/smf/src
  ${PROJECT_BINARY_DIR}/smf/src/third_party/flatbuffers/include)

add_executable(verved server.cc ${verve_fbs_OUTPUTS})
target_link_libraries(verved smf)
```

**Comment by noahdesu** [comment]
regarding ExternalProject_Add, is that in reference to a smf dependency, or using smf as a dependency in another project?

**Comment by senior7515** [comment]
Oh thanks for the cmake for 3rd party use of smf. 

I was refering to the fact that every time i run ./debug for example

zstd* links and builds all the man pages. 

I looked into it and it doesn't define CMAKE_* vars to disable things like smf does. 

Also 

Histogram_c project adds the unit tests to the parent repo as well as flatbuffers.

**Comment by noahdesu** [comment]
Ahh, gotcha.

The way I see this typically handled in other projects is to:

1) fork all sub-module dependencies (e.g. github.com/smf/{zstd, googletest, etc...}). this lets you pin a particular revision _and_ avoid issues with upstream versions changing on accident.

2) add basic cmake changes you want on top of the target revision for smf

3) submit PRs upstream for those build changes.

**Comment by noahdesu** [comment]
Circling back around to `ExternalProject_Add`: to avoid having hdr histogram adding the unit tests, then your suggestion about external project add should work just fine. For things like building man pages, if the option simply doesn't exist, then changes need to be made in that project's cmake build.

**Comment by senior7515** [comment]
Yeah agreed. It actually increases incremental builds by 3 seconds which is about 25% 

```
cd ~/workspace/smf/build_debug/; ninja -j1
[1/19] Creating pkg-config file
[2/19] Creating unzstd symlink
[3/19] Creating zstdmt symlink
[4/19] Creating zstdcat symlink
[5/19] Copying manpage zstd.1
[6/19] Creating unzstd.1 symlink
[7/19] Creating zstdcat.1 symlink
[8/19] Building CXX object src/rpc/CMakeFiles/smf_rpc.dir/rpc_recv_context.cc.o
...

```

**Comment by noahdesu** [comment]
This patch here is working OK for me to disable quite a few things.

https://github.com/noahdesu/smf/commit/89c916144f50d57d0d4662a81abd0fd412c3e30f

I'm not seeing the man pages being built in zstd...

**Comment by senior7515** [comment]
.... you are amazing! let's merge that. Can you make a PR. 

I also just fixed some safety mechanisms for load shedding that seemed to be working, that you might wanna pull anyways.

**Comment by noahdesu** [comment]
yeh, i'll fold that into a new patch set soon

**Comment by noahdesu** [comment]
well that was easy https://github.com/HdrHistogram/HdrHistogram_c/commit/106bb571a47da1d0ddb213298321ec7cb73530c8

**Comment by senior7515** [comment]
:) so much goodness in this !!! thanks! 

PS. I see master is failing on travis - due to a seastar master update :( will fix tonight, it builds fine on my machine from scratch.

**Comment by senior7515** [comment]
@noahdesu  you basically fixed all the issues w/ the last PR. thanks. closing this issue.
