### ISSUE TITLE
smf build fails on linux mint 18

### ISSUE THREAD

**Issue by crackcomm** [senior7515/smf#214]
`c++ (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519`.

[build log](https://gist.github.com/crackcomm/05c30f41ab6d5f49ccfab2878728ad6a)

I tried installing g++-7
`c++ (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0`

[build log](https://gist.github.com/crackcomm/5b0d2e069f4d58b14b4cd0a7840c7cbc)

**Comment by senior7515** [comment]
Got it! thanks. looking into it.

**Comment by crackcomm** [comment]
@senior7515 I kept looking and I see `/usr/include/c++/6` - probably it?

**Comment by senior7515** [comment]
could be, i've tested w/ gcc6. 

can you `cd build_debug && ninja -j1`

**Comment by crackcomm** [comment]
I did `sudo mv /usr/include/c++/6 /usr/include/c++/6-not-used` and `cd build_debug && ninja -j1`, same error.

**Comment by crackcomm** [comment]
exact log: https://gist.github.com/crackcomm/6e80afb82de7e00f6035f3aa4095df57

**Comment by senior7515** [comment]
seastar is failing, https://travis-ci.org/scylladb/seastar/jobs/347447890

can you try this git hash: on seastar: 0ed15e9

**Comment by crackcomm** [comment]
@senior7515 this is weird, seastar compiled fine, earlier with g++ 6.3.0.

I will try at `0ed15e9`.

**Comment by noahdesu** [comment]
that's weird. the seastar version is pegged in ci (https://github.com/senior7515/smf/blob/master/ci/base/Dockerfile#L13), i wonder why its failing on travis

**Comment by crackcomm** [comment]
here is the log this time: https://gist.github.com/crackcomm/3285f7c45071ec98f6ec9d7f90706353

**Comment by senior7515** [comment]
thanks @crackcomm ... pretty helpful. Trying to repro locally.

**Comment by senior7515** [comment]
@noahdesu  - good point. will try to build locally at this revision and see if I can repro

**Comment by senior7515** [comment]
good news, is I can repro at that git hash of seastar!

**Comment by senior7515** [comment]
fix on the way. thanks!

**Comment by crackcomm** [comment]
@senior7515 thanks, in fact it fixed the error

still, the previous error remains: https://gist.github.com/crackcomm/7f83ed85c6f50897c5f384614c70be6e

**Comment by senior7515** [comment]
ok that's good. (re: bugfix/ci). Have you by chance tried the latest seastar hash now that that bug is gone, and or the one on the dockerfile. 

once i can get a reproducible bug on my machine, I can fix it. 

thanks!

**Comment by crackcomm** [comment]
seastar master log: https://gist.github.com/crackcomm/b0bd049ec294869eddaea35c202b813b

**Comment by noahdesu** [comment]
Perhaps we can reproduce in docker. Are you running Linux mint? Which
version etc?

**Comment by crackcomm** [comment]
Linux Mint 18.2 Sonya

**Comment by senior7515** [comment]
Will try to repro w/ docker. thanks @crackcomm !

**Comment by crackcomm** [comment]
let me know if I can be helpful somehow

**Comment by senior7515** [comment]
tried running on docker, and not getting very far tonight...  :'( will keep hacking on it this week. 

I did notice a few things. linux mint 18 is basically ubuntu xenial which we build against and it works. 
it also comes with gcc 4.8 - very old. 

do you mind manually setting these 2 variables

```
SET(CMAKE_C_COMPILER /path/to/c/compiler)
SET(CMAKE_CXX_COMPILER /path/to/cpp/compiler)
``` 

to a later gcc - say gcc6 to test it out.

**Comment by senior7515** [comment]
I tried building on this: https://hub.docker.com/r/linuxmintd/mint18-amd64/tags/

**Comment by senior7515** [comment]
@crackcomm let me know if you manage to push a docker image and I will fix it tonight.

**Comment by crackcomm** [comment]
@senior7515 I am going to test it out, with gcc-6

I already have some weird noise in here:

```
➜  seastar git:(master) ✗ python3 configure.py --compiler=g++-6
Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.
Notice: disabling -Wattributes due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947
Seastar requires g++ >= 4.9.  Install g++-4.9 or later (use --compiler option).
```

g++-7:

```
➜  seastar git:(master) ✗ python3 configure.py --compiler=g++-7
Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.
Notice: disabling -Wattributes due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947
```

I am having some trouble with CMake, I will re-pull and build.

What would you want me to include in a Docker image?

**Comment by crackcomm** [comment]
Is there some easy way to build a docker image from my entire OS?

**Comment by crackcomm** [comment]
I think this has to be some incompatibility with C++ tool-chain in Mint packages.

Here is my [repos list](https://gist.github.com/crackcomm/3ee4c6d05bd2043e706253d637dea42d), can't find a good, other image of mint than you found.

I am now rebuilding seastar with gcc-6 and later smf with gcc-6, previously there might've been some incompatibility as I had to update CMake to build smf and later install g++-7.

I have to admit the error from the C++ compiler does not make too much sense for me but correct me if I'm wrong, this is error origins from seastar source code `distributed.hh` and `httpd.hh` and not in smf? It seems odd because seastar compiled fine and I even made a [quick comparison](https://gist.github.com/crackcomm/9edd2d48137a1dec3c42879b539e17f9) between seastar `httpd` ad Go `net/http`.

I wish I could help more but I am not sure what I can do, thank you for your support.

**Comment by crackcomm** [comment]
I tried to build on Ubuntu 16.04 in Docker on VPS, here is the build [log](https://gist.github.com/crackcomm/0a7033374fa2ef15208cb6d725dfa81c). reproducable easily with [history](https://gist.github.com/crackcomm/93edbd96c3781eac43e53ae7540e8e0b) which includes installing dependencies from seastar `install-dependencies.sh` and smf `install-deps.sh`.

**Comment by noahdesu** [comment]
i removed xenial from travis-ci at some point as either (1) stock gcc was too old or (2) needed some additional setup in cmake. that would explain the issue, as i thought xenial was still active in ci. we should add a xenial config to the travis config file

**Comment by noahdesu** [comment]
https://travis-ci.org/noahdesu/smf/jobs/348003612

**Comment by crackcomm** [comment]
@noahdesu both :)

I was able to build on docker image mentioned previously by doing

```console
apt-get remove g++-5
apt-get install g++-7-multilib
apt autoremove
```

**Comment by noahdesu** [comment]
cool cool. so, this is really easy to hack into the travis-ci for on going testing. thanks for narrowing this down. in terms of fixes, i wonder if this is just a documentation fix: "if you are using xenial or mint, you need to upgrade gcc" ?

**Comment by crackcomm** [comment]
also remove old libstdc++

**Comment by noahdesu** [comment]
_maybe_ can skip removing g++5 and libstdc++ by using update-alternatives, but haven't tested: https://github.com/ceph/ceph/blob/master/install-deps.sh#L63

**Comment by crackcomm** [comment]
it only updates binaries location not libstdc++ and only after removing it it worked out. if you could somehow do same with libraries then it could work out

**Comment by crackcomm** [comment]
problem is also `apt-get install -qy g++-7` does not install these std libs but `apt-get install g++-7-multilib`

**Comment by senior7515** [comment]
thank you @crackcomm  - great tracking down!!! let's definitely track this in the travis script! 

w00t! excited to have you up and running!

**Comment by senior7515** [comment]
@crackcomm - are you thinking of submitting a PR for the multilib and ubunu:xenial ?

**Comment by crackcomm** [comment]
@senior7515 I am not sure, do you mean adding install in `ci/base/Dockerfile` and `ubuntu:xenial` in `.travis.yml`? or install in `install-deps.sh`?

**Comment by senior7515** [comment]
oh just thinking of getting `.travis.yml` working with `ubuntu:xenial`
