### ISSUE TITLE
Go support for smf_gen

### ISSUE THREAD

**Issue by crackcomm** [senior7515/smf#218]
I just started [go-smf](https://github.com/crackcomm/go-smf/) implementation. Go is missing flatbuffers parser so now I was thinking about using `smf_gen` to do that, do you have any thoughts?

**Comment by senior7515** [comment]
Awesome!, would be great addition to the main repo when it works too.

smf_gen would get a good candidate to host the code generation for all languages -  the benefits is that all languages use the cpp parser, and we use the same parser that the main project uses. 


Let me try to give you a couple of pointers: https://gist.github.com/105307547f9cb7eab30813443d862a20


```cpp
// Generated by the smf_gen.
// Any local changes WILL BE LOST.
// source: /home/agallego/workspace/smf/src/demo_apps/demo_service
#pragma once
#ifndef SMF_DEMO_SERVICE_INCLUDED
#define SMF_DEMO_SERVICE_INCLUDED
#include "demo_service_generated.h"

#include <core/sstring.hh>
#include <experimental/optional>
#include <rpc/rpc_service.h>
#include <rpc/rpc_client.h>
#include <rpc/rpc_recv_typed_context.h>
#include <rpc/rpc_typed_envelope.h>
#include <platform/log.h>

namespace smf_gen {
namespace demo {

class SmfStorage: public smf::rpc_service {
 private:
  std::vector<smf::rpc_service_method_handle> handles_;
 public:
  ~SmfStorage() = default;
  SmfStorage() {
    handles_.emplace_back(
      "Get", 1719559449,
      [this](smf::rpc_recv_context c) -> seastar::future<smf::rpc_envelope> {
        // Session accounting
        auto session_id = c.session();
        return RawGet(std::move(c)).then([session_id](auto e){
          e.letter.header.mutate_session(session_id);
          return seastar::make_ready_future<smf::rpc_envelope>(std::move(e));
        });
    });
  }
  virtual const char *
  service_name() const override final {
    return "SmfStorage";
  }
  virtual uint32_t
  service_id() const override final {
    return 212494116;
  }
  virtual const std::vector<smf::rpc_service_method_handle> &
  methods() override final {
    return handles_;
  }
  virtual smf::rpc_service_method_handle *
  method_for_request_id(uint32_t idx) override final {
    switch(idx){
      case (212494116 ^ 1719559449): return &handles_[0];
      default: return nullptr;
    }
  }
  inline virtual
  seastar::future<smf::rpc_typed_envelope<smf_gen::demo::Response>>
  Get(smf::rpc_recv_typed_context<smf_gen::demo::Request> &&rec) {
    using out_type = smf_gen::demo::Response;
    using env_t = smf::rpc_typed_envelope<out_type>;
    env_t data;
    //
    //
    // USER SHOULD OVERRIDE THIS METHOD.
    //
    //
    // Helpful for clients to set the status.
    // Typically follows HTTP style. Not imposed by smf whatsoever.
    // i.e. 501 == Method not implemented
    data.envelope.set_status(501);
    return seastar::make_ready_future<env_t>(std::move(data));
  }
  inline virtual
  seastar::future<smf::rpc_envelope>
  RawGet(smf::rpc_recv_context &&c) {
    using inner_t = smf_gen::demo::Request;
    using input_t = smf::rpc_recv_typed_context<inner_t>;
    return Get(input_t(std::move(c))).then([this](auto x){
      return seastar::make_ready_future<smf::rpc_envelope>(x.serialize_data());
    });
  }
}; // end of service: SmfStorage

class SmfStorageClient:
  public smf::rpc_client,
  public seastar::enable_shared_from_this<SmfStorageClient> {

  private:
    SmfStorageClient(seastar::ipv4_addr server_addr)
    :smf::rpc_client(std::move(server_addr)) {}
    SmfStorageClient(smf::rpc_client_opts o)
    :smf::rpc_client(std::move(o)) {}

  public:
    static seastar::shared_ptr<SmfStorageClient>
    make_shared(seastar::ipv4_addr addr) {
      SmfStorageClient c(std::move(addr));
      return seastar::make_shared<SmfStorageClient>(std::move(c));
    }
    static seastar::shared_ptr<SmfStorageClient>
    make_shared(smf::rpc_client_opts o) {
      SmfStorageClient c(std::move(o));
      return seastar::make_shared<SmfStorageClient>(std::move(c));
    }
    SmfStorageClient(SmfStorageClient &&o) = default;
    ~SmfStorageClient() {}
    virtual const char *name() const final {
      return "SmfStorageClient";
    }
    virtual seastar::shared_ptr<rpc_client> parent_shared_from_this() final {
      return shared_from_this();
    }
    inline virtual
    seastar::future<smf::rpc_recv_typed_context<smf_gen::demo::Response>>
    Get(smf::rpc_envelope e) {
      /// RequestID: 212494116 ^ 1719559449
      /// ServiceID: 212494116 == crc32("SmfStorage")
      /// MethodID:  1719559449 == crc32("Get")
      e.set_request_id(212494116 ^ 1719559449);
      return send<smf_gen::demo::Response>(std::move(e));
    }
    inline virtual
    seastar::future<std::experimental::optional<smf::rpc_recv_context>>
    RawGet(smf::rpc_envelope e) {
      /// RequestID: 212494116 ^ 1719559449
      /// ServiceID: 212494116 == crc32("SmfStorage")
      /// MethodID:  1719559449 == crc32("Get")
      e.set_request_id(212494116 ^ 1719559449);
      return raw_send(std::move(e));
    }
  }; // end of rpc client: SmfStorageClient

}  // namespace demo
}  // namespace smf_gen


#endif  // SMF_DEMO_SERVICE_INCLUDED

```

**Comment by senior7515** [comment]
The main methods that the  go generator will implement (doesn't have to implement all of the ones the c++ does at the moment)


# most important one is manually generating the jump table. This had a 20% latency reduction from the fastest hash table in c++

```cpp

  virtual smf::rpc_service_method_handle *
  method_for_request_id(uint32_t idx) override final {
    switch(idx){
      case (212494116 ^ 1719559449): return &handles_[0];
      default: return nullptr;
    }
  }

```
# the corresponding client code for the method

```cpp

    inline virtual
    seastar::future<smf::rpc_recv_typed_context<smf_gen::demo::Response>>
    Get(smf::rpc_envelope e) {
      /// RequestID: 212494116 ^ 1719559449
      /// ServiceID: 212494116 == crc32("SmfStorage")
      /// MethodID:  1719559449 == crc32("Get")
      e.set_request_id(212494116 ^ 1719559449);
      return send<smf_gen::demo::Response>(std::move(e));
    }
```

**Comment by senior7515** [comment]
the whole RPC is basically around those 2 methods - that's it. Is really quite simple. We can add filters later, headers, and other checks - but this will get you a `hello-world`. 

notice that `&handles_[0]` doesn't have to have a 1-1 translation in go. it can return a receiver that wraps the client code.

**Comment by senior7515** [comment]
One design decision you might have to make, that we can probably model after the gRPC code generators  is do you handle multiple executions of the same methods via a `mutex.Lock(); defer mutex.Unlock()` or do you do something like this: https://blog.golang.org/context and add some form of gorutine local storage.

I bet the gRPC code is probably a good starting point for ideas.

**Comment by senior7515** [comment]
The way forward with this, is first, I'd manually code the example server and client in Go - the smallest thing that can work.

Once you have this ideal client/server with these 2 methods above, i can help you with the code generation, or I can point at you how to generate code. 

In general you can use *most* of the infrastructure already. So you would just have to write a file like this:
https://github.com/senior7515/smf/blob/master/src/rpc/smf_gen/cpp_generator.cc

**Comment by crackcomm** [comment]
@senior7515 thanks, points you made are very helpful.

I think most of this can happen without locks and that would depend on user service implementation.

I just got caught on basics and not sure what's going on here - https://play.golang.org/p/GHvXd17fqon is something wrong with Go's crc32 implementation or am I missing something? the hash for `SmfStorage` is correct but not for `Get` maybe you could quickly point out the mistake? wrong table?

**Comment by senior7515** [comment]
@crackcomm  - here I fixed it for you. 

Turns out, I had to use the fully qualified name for symbol collision and I didn't document it. 

Also, on Go you have to manually make the table... not sure why

https://play.golang.org/p/nHFXDQ0oVEM

**Comment by senior7515** [comment]
Here is the code

https://github.com/senior7515/smf/blob/master/src/rpc/smf_gen/smf_method.h#L21-L23

But no worries, this is the infrastructure that you would get for free once we write the code generation w/ smf_gen. 

All of this is already handled for you. 

So it's ok to hack it for now, once you have the template of what the output should look like we can start iterating on it.

**Comment by crackcomm** [comment]
wow, thanks, it explains a lot, I couldn't find that in the code, guess I was searching for `crc32` not `crc_32`.

not sure why you had to make the table manually; https://play.golang.org/p/7Sujb7YcEwu

**Comment by senior7515** [comment]
Sorry. Fat finger click

**Comment by crackcomm** [comment]
I have some [storage service](https://github.com/crackcomm/go-smf/blob/master/example/demo_gen/storage_service.go) beginnings, for the server. Client is still something I'm thinking through, not yet sure how to deal with it efficiently.

**Comment by senior7515** [comment]
@crackcomm let me know if you need guidance on this. 

I'd say we can get something working first, then we can optimize it. 

Basically, the strategy should be this - i think the rest will fall into place after. 

* https://github.com/crackcomm/go-smf/blob/master/rpc/server.go#L30

u need to do: 

1) Parse 16 bytes - add a method that taking a connection, it will return *exactly* some number of bytes

```go

ReadExactly(conn *rpc.connection, read_bytes: uint32_t): []byte {
     char payload[read_bytes];    
while( read_bytes > 0) {
          read = conn.read(read_bytes)
          payload [ current: len(read)] = read
           read_bytes -= len(read)
        }
       return payload[:]

}

```

**Comment by crackcomm** [comment]
1. method is [here](https://github.com/crackcomm/go-smf/blob/master/rpc/header_utils.go#L20)

demo server is currently in [demo_server](https://github.com/crackcomm/go-smf/blob/master/example/demo_server/server.go#L45).

I tested both `demo_server` and `demo_client` with smf demo_apps. Both work, except they miss on session management.

**Comment by crackcomm** [comment]
code from demo_server will eventually end up in the place you pointed out.

although, Go implementation of flatbuffers is not as elegant as the C++ one, hence you see `[]byte` or `*flatbuffers.Builder` passed around in Go flatbuffers RPC frameworks.

**Comment by senior7515** [comment]
oh got it! very cool. 

to handle sessions just add this here: https://github.com/crackcomm/go-smf/blob/master/example/demo_server/server.go#L66

```go

....

	resp, err := handle(context.TODO(), reqBuf)
	if err != nil {
		panic(err)
	}

	respHdr := rpc.BuildResponseHeader(hdr, resp, 200)

	// debug: print response header
	rhdr := new(rpc.Header)
	rhdr.Init(respHdr, 0)

...

>>>> Here
        rhdr.session = hdr.session
```

**Comment by senior7515** [comment]
In any case, this is pretty neat. 

Once you clean it up, let's maybe plan to get the generators working next weekend?

**Comment by crackcomm** [comment]
It's already done in `BuildResponseHeader` :100: 

I meant it does not have the ability to multiplex req-rep based on a session but thanks anyway :+1: 

I think we can get generators working, there will be more work on the actual client/connection/dispatch side.

**Comment by senior7515** [comment]
I have some ideas to make sure that the go GC doesn't play in it. roughly speaking, we can get the flatcc (the C version generator) and then bind it w/ the unsafe package in Go, if it becomes a bottleneck. 

i need to benchmark once we have the generators.

**Comment by crackcomm** [comment]
I actually wanted to ask you about this, today.

In C++ server bind RPC handlers from Go package, it's interesting.

**Comment by crackcomm** [comment]
I think Go->C calls can sometimes be much more expensive than native Go code.

For example I noticed `strings.Split` in Go are 10x faster than `boost::split` when splitting fs path. Go is pretty fast.

Most of the benefit I believe could be achieved by using seastar loop to call Go functions. I didn't thought about this much, about sharding, splitting runtimes, mutexes or whatever. I think it's doable though.

**Comment by senior7515** [comment]
boost::split is fast, i bet the latency would come from not big enough strings or std::string itself. try with strings with the small type optimization.

re: seastar-loop - not sure it will work, i think there would be an issue w/ the allocator. seastar owns the full memory, so not sure how the Go runtime will have memory to be allocated for the GC, and how to communicate that info. I bet some LD_PRELOAD magic might help - not sure - but let's test. 

Before we get there tho, we need a baseline. I actually think that the Go TCP path is pretty well optimized, so running seastar w/out DPDK *might* have some perf benefits, but maybe not as large as one might think. 

It would be cool to hack the Go runtime to run one full Go VM *per* core. This would work. 

Now that you have the bones up and running, how do you want to tackle the generators ? 

I tried making the build system for the generator pretty friendly - no need to build anything else now. https://github.com/senior7515/smf/blob/master/src/smfc/README.md

**Comment by senior7515** [comment]
also w.r.t passing around []byte - i wrote a quick wrapper that does that basically:

https://github.com/senior7515/smf/blob/master/src/include/smf/fbs_typed_buf.h#L24-L29

in go it should be somthing like 

```
type FBSTyped {
  data: []byte;
}

type MyGeneratedType { FBSTyped } // generated by complier
func (t *MyGeneratedType) MyGeneratedMethod() {   // generated by compiler
        x := cast_to_type( data )
        return x->MyGeneratedMethod()
}
```

**Comment by senior7515** [comment]
anyway, very cool, let me know if you get stuck w/ the generator.

**Comment by crackcomm** [comment]
yes, indeed strings were very small, I need to check with seastar string, for example. thanks

I bet we could create a `sharded<>` Go runtime pretty easily, one per core.

Thanks for making it easier to build, it definitely helps.

I am not sure `fbs_typed_buffer` will be as useful in Go, I've seen this in code but in Go...not sure yet

maybe we should use resp.[Table()](https://github.com/crackcomm/go-smf/blob/master/example/demo/Response.go#L25).[ByteVector(0)](https://github.com/google/flatbuffers/blob/master/go/table.go#L34) or [.Bytes](https://github.com/google/flatbuffers/blob/master/go/table.go#L7)

**Comment by crackcomm** [comment]
I want good client interface and I will start the `go_generator.cpp` :)

**Comment by senior7515** [comment]
@crackcomm let me knokw if you need help now that you have the basic structure up.

**Comment by senior7515** [comment]
Ping. Any help I can provide

**Comment by crackcomm** [comment]
@senior7515 sorry but I was sick lately, I'll come back to you I promise :)

2018-03-23 18:00 GMT+01:00 Alexander Gallego <notifications@github.com>:

**Comment by crackcomm** [comment]
@senior7515 sure, is there any chance you could transpile [generated](https://github.com/crackcomm/go-smf/tree/master/example/demo_gen) code into C++ generator? If any changes will occur they will probably be very slight.

**Comment by crackcomm** [comment]
I think they could be all in a single file.

**Comment by crackcomm** [comment]
In case you would like to merge the code just do it your way :)

**Comment by senior7515** [comment]
will post here when i have a patch, i can try to hack something in the next couple of days.

**Comment by crackcomm** [comment]
okay, cool

**Comment by senior7515** [comment]
I started hacking something here, but taking the time to do some TLC on that code base and adding tests too. 

https://github.com/senior7515/smf/pull/227/commits/beb08593ca5ed2beb3b84ef2372ad1d4a83eb81c

so, might take a bit longer, but will ping you as soon as I have something that compiles. 

you are welcome to keep an eye on it too.

**Comment by senior7515** [comment]
@crackcomm  - i just finished the structure to add the go generator and any language generator, all i have to do now is add the print() statements to the file and that's it. 

Stay put for follow up patch.

**Comment by senior7515** [comment]
I have the server side generating correctly. need to generate the client side next. 

https://gist.github.com/7201e8eafb447799e853296fc824494e

want to submit a PR with your changes to a feature branch and I can pull them into my branch or vice versa.

**Comment by senior7515** [comment]
you should be able to run the generator via:
(something like this)

```
/home/agallego/workspace/smf/build_debug/src/smfc/smfc \ 
        --logtostderr \
        --filename /home/agallego/workspace/smf/demo_apps/demo_service.fbs \
       --output_path=/home/agallego/workspace/smf/build_debug/src/integration_tests \
       --language=go
```

**Comment by senior7515** [comment]
actually @crackcomm can you use this PR/branch instead. sorry, did some minor cleanup

https://github.com/senior7515/smf/tree/feature/golang_generator

**Comment by senior7515** [comment]
hey @crackcomm  - ping 

not sure if you've seen that i merged alpha support for codegen for go. 

is there anything I need to do to support you ? this patch is pretty cool and wanna get it merged.

let me know. 

.alex

**Comment by crackcomm** [comment]
hey, thanks, I didn't, I will look into it tomorrow

2018-04-27 1:44 GMT+02:00 Alexander Gallego <notifications@github.com>:

**Comment by senior7515** [comment]
cool no problem. I expect that you might need to modify a couple of small things tho. 

but here is the only file you would hopefully only need to modify the text, i did match what you posted on your PR, so hopefully it just works, but likely that it needs a couple of small patches too. 

let me know. i can help this weekend. 

w00t.

**Comment by senior7515** [comment]
sry, closed issue by mistake,

**Comment by crackcomm** [comment]
@senior7515 I found just two issues at first glance,

1. missing `package demo` on the top of the generated file
2. output type name `smf_gen.demo.Response` is illegal

**Comment by crackcomm** [comment]
at second glance maybe new lines between definitions, to match the output after `gofmt`.

**Comment by crackcomm** [comment]
oh,

```Go
func (s *SmfStorageService) ServiceID() uint32 {
	return "212494116"
}
```

**Comment by senior7515** [comment]
https://gist.github.com/b118b785395a9648458699d51370e2c2

**Comment by senior7515** [comment]
@crackcomm  - fixing the top level package next and that should do it.

**Comment by senior7515** [comment]
@crackcomm  the last commit should do it.

**Comment by senior7515** [comment]
hey @crackcomm  let me know if you need anything else. I fixed all the bugs you brought up. it's merged in master so just pull and rebuild.

**Comment by crackcomm** [comment]
Im stuck on windows and so it takes more time. I will build a VM tomorrow, what OS do you recommend to make it as easy as possible?

**Comment by senior7515** [comment]
fedora27 is probably best. It's just this: 

`git clone --recursive ... && cd src/third_party/seastar && ./install-dependencies.sh && cd smf ./install-deps.sh && ./debug`

**Comment by senior7515** [comment]
hi @crackcomm  did you get a chance to test the latest changes?

**Comment by senior7515** [comment]
@crackcomm  do you mind if I give this integration a shot? If you are doing it, i'd love for you to finish it, but wanted to test to see how far we are from having a working go client integration. let me know.

**Comment by senior7515** [comment]
@crackcomm  - i just merged support and build system support for Go 

I will be adding your sample demos this weekend. 

But this should be almost ready for public consumption. 

now that we have @KowalczykBartek  who also just contributed the Java bindings

We should start working on perf benchmarks across languages.

Would be kind of fun and maybe we can port performance tips around.
