### ISSUE TITLE
Support 2-way RPC on the same connection, where both sides can act as both client and server

### ISSUE THREAD

**Issue by zuowang** [senior7515/smf#237]
I am going to implement a parameter server based on smf, where the Master has to wait for all Workers and Servers to register, and send back ACK after that. I have no way to work with smf.

**Comment by senior7515** [comment]
@zuowang  - you can test it now - seastar is up and working now https://travis-ci.org/senior7515/smf/jobs/384467814

**Comment by zuowang** [comment]
@senior7515  Tons of thanks!
I can't figure out how the bi-directional channel works.
I can find the connection in rpc_server.cc:92, but I don't know how to get it, and send Response to client.
```
  seastar::keep_doing([this] {
    return listener_->accept().then([ this, stats = stats_, limits = limits_ ](
      seastar::connected_socket fd, seastar::socket_address addr) mutable {
      auto conn = seastar::make_lw_shared<rpc_server_connection>(
        std::move(fd), limits, addr, stats, ++connection_idx_);

      open_connections_.insert({connection_idx_, conn});

      // DO NOT return the future. Need to execute in parallel
      handle_client_connection(conn);
    });
  })
```

**Comment by zuowang** [comment]
Many Thanks! I will try it later.

**Comment by senior7515** [comment]
@zuowang  check this demo project out https://github.com/senior7515/smf/tree/master/demo_apps

**Comment by FanFansfan** [comment]
Maybe "2-way RPC" means a client can connect to a server and then client use some mechanisms to setup callbacks, server will **invoke "callback" on client** / **push data to client** when some events occur, these "response"s do not have corresponding client side "request"s. In this way the above two nodes can have a "Full Duplex" inter-connection using one underlying tcp socket.

While currently it seems the only solution to this situation is to setup a rpc_service on client side node, and server side node connect this rpc_service to invoke "callback" / push data.

**Comment by senior7515** [comment]
@FanFansfan thanks for chiming in. Yeah, this is not too hard to setup, and I would say about 90% of the code is there already. 

Let me know if you would like to contribute it. The server as it exists today is already doing full streaming, and the client as it exists today is also always looking for data. 

The  missing pieces are: 

1. To re-enqueue a future for every processed future. 
2. Add a bitflag to the header to let the server add a callback to push arbitrary data

This is a medium-difficulty task. Let me know if you would like to tackle the first pass at this. 

Thanks!
