### ISSUE TITLE
[question ] What makes SMF an order faster than other RPC system?

### ISSUE THREAD

**Issue by syang** [senior7515/smf#260]
I am interested in finding the key factor that make SMF latency (p99) so low comparing other RPC mechanism like Thrift and gRPC.

does that required special network stack such as DPDK or does it bypass some networking stack?

I'd appreciate if someone give a thorough list of the reason

**Comment by senior7515** [comment]
I gave a talk here: http://www.scylladb.com/2017/11/15/smf-fastest-rpc/

But high level: 
* no locks (actually very few if you count the kernel's NIC lock  + SIRQ)
* small
* binary
* no deserialization
* seastar
* optional DPDK
* All features were measured / profiled w/ perf. AFAIK. 

The code is around 3K - it is very small, so you can read it. 
Additionally from the code that does the RPC I wrote a compiler smfc (which takes in a .fbs schema) and generates seastar future based code - but really - that's optional.

**Comment by senior7515** [comment]
Please profile it yourself and or measure. If you find any bottleneck let me know and I'll try to fix.

**Comment by senior7515** [comment]
@syang  let me know if you have other questions. Also, feel free to use the mailing list. - it's in the readme.
