### ISSUE TITLE
Use smf as an installed library

### ISSUE THREAD

**Issue by lgarithm** [senior7515/smf#283]
**Is your feature request related to a problem? Please describe.**
I'm building an application with C++ and would like to use smf for RPC.
My project is using CMake for building, and it has a `CMakeLists.txt` in its root folder.
I built smf and installed it with the following script,

```bash
#!/bin/bash
set -e

mkdir -p $HOME/tmp
cd $HOME/tmp

[ ! -d smf ] && git clone https://github.com/senior7515/smf.git --recursive -j16

PREFIX=$HOME/local/smf  # the install location
ROOT=$(pwd)/smf
BUILD_DIR=$(pwd)/build-smf/release

cd ${ROOT}

git submodule update --init

install_smf() {
    mkdir -p $BUILD_DIR
    cd ${BUILD_DIR}

    cmake ${ROOT} \
        -Wno-dev \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=${PREFIX} \
        -DSMF_ENABLE_TESTS=OFF \
        -DSMF_BUILD_PROGRAMS=OFF \
        -DSEASTAR_ENABLE_DPDK=ON

    make -j 6
    make install
}

install_smf
```
And then I add the following in `CMakeLists.txt` (it is common for a typical C/C++ lib)
```cmake
SET(SMF_PREFIX $ENV{HOME}/local/smf)
INCLUDE_DIRECTORIES(${SMF_PREFIX}/include)
LINK_DIRECTORIES(${SMF_PREFIX}/lib)
```
But the installed smf is missing headers from 3rdparty, e.g.
```
/home/vagrant/local/smf/include/smf/histogram_seastar_utils.h:7:10: fatal error: core/fstream.hh: No such file or directory
 #include <core/fstream.hh>
```

The demo app in smf doesn't have such problem, because the `CMakeLists.txt` in smf has `add_subdirectory` recursively for all its dependencies.

**Describe the solution you'd like**
Make it easier to use smf as an installed lib.

**Describe alternatives you've considered**
Provide CMake Modules such that users can include in their `CMakeLists.txt`, to ensure all depend include dirs are included.

**Additional context**
N/A.

**Comment by senior7515** [comment]
Clone this repo and just do ./build.sh should give you a working build w/ artifacts 

https://github.com/senior7515/smf-getting-started-cpp

**Comment by senior7515** [comment]
@lgarithm   give this a test and let me know.

**Comment by lgarithm** [comment]
@senior7515 I've successfully built and run this project, it works perfectly well and completely meets my requirement. 
Thank you very much!

**Comment by senior7515** [comment]
great to hear

**Comment by lgarithm** [comment]
@senior7515 I'm working on the same project as @luomai mentioned https://github.com/senior7515/smf/issues/282#issuecomment-434284939
